<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="testNGFramework" duration-ms="7924" started-at="2020-10-18T16:44:58Z" finished-at="2020-10-18T16:45:06Z">
    <groups>
    </groups>
    <test name="DemoBlazeSignupLogin" duration-ms="7924" started-at="2020-10-18T16:44:58Z" finished-at="2020-10-18T16:45:06Z">
      <class name="testNGFramework.DemoBlazeplaceOrder">
        <test-method status="FAIL" signature="a_placeOrder()[pri:0, instance:testNGFramework.DemoBlazeplaceOrder@29ee9faa]" name="a_placeOrder" duration-ms="1" started-at="2020-10-18T16:45:06Z" finished-at="2020-10-18T16:45:06Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at testNGFramework.DemoBlazeplaceOrder.a_placeOrder(DemoBlazeplaceOrder.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a_placeOrder -->
        <test-method status="FAIL" signature="b_checkOut()[pri:0, instance:testNGFramework.DemoBlazeplaceOrder@29ee9faa]" name="b_checkOut" duration-ms="4" started-at="2020-10-18T16:45:06Z" finished-at="2020-10-18T16:45:06Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at testNGFramework.DemoBlazeplaceOrder.b_checkOut(DemoBlazeplaceOrder.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b_checkOut -->
      </class> <!-- testNGFramework.DemoBlazeplaceOrder -->
      <class name="testNGFramework.DemoBlazeSignupLogin">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testNGFramework.DemoBlazeSignupLogin@6767c1fc]" name="beforeSuite" is-config="true" duration-ms="14167" started-at="2020-10-18T16:44:44Z" finished-at="2020-10-18T16:44:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="a_signUp()[pri:0, instance:testNGFramework.DemoBlazeSignupLogin@6767c1fc]" name="a_signUp" duration-ms="5471" started-at="2020-10-18T16:44:58Z" finished-at="2020-10-18T16:45:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a_signUp -->
        <test-method status="PASS" signature="b_login()[pri:0, instance:testNGFramework.DemoBlazeSignupLogin@6767c1fc]" name="b_login" duration-ms="2406" started-at="2020-10-18T16:45:04Z" finished-at="2020-10-18T16:45:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b_login -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testNGFramework.DemoBlazeSignupLogin@6767c1fc]" name="afterSuite" is-config="true" duration-ms="3487" started-at="2020-10-18T16:45:06Z" finished-at="2020-10-18T16:45:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
        <test-method status="FAIL" signature="afterSuite()[pri:0, instance:testNGFramework.DemoBlazeplaceOrder@29ee9faa]" name="afterSuite" is-config="true" duration-ms="0" started-at="2020-10-18T16:45:10Z" finished-at="2020-10-18T16:45:10Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at testNGFramework.DemoBlazeplaceOrder.afterSuite(DemoBlazeplaceOrder.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testNGFramework.DemoBlazeSignupLogin -->
    </test> <!-- DemoBlazeSignupLogin -->
  </suite> <!-- testNGFramework -->
</testng-results>
